### ISSUE TITLE
Implement a batch job of updating stars

### ISSUE THREAD

**Issue by taihaku** [k0kubun/gitstar-ranking#13]
- [x] grab the big picture of UserFetchJob
- [ ] implement job updating all user stars
- [ ] apply it others

**Comment by bmkmanoj** [comment]
+1

**Comment by lipis** [comment]
http://githubstats.lip.is and it's also open source but in a completely different technology.. let's just redirect it there :)

**Comment by k0kubun** [comment]
Since your website calculates only top 1024 ranks and excludes others including me, not only technology but also contents are different. I'm sorry for the late update but why should I redirect my website to the one that excludes my information? So there is no reason to redirect it there.

**Comment by lipis** [comment]
http://githubstats.lip.is/k0kubun you are not excluded.. and you will never going to have accurate rankings unless you are scrapping GitHub every single day for all 3M+ users.. which is let's admit impossible.. or pointless..

and at the moment.. because it's so outdated and not being updated is very confusing and misleading..
<img width="1155" alt="screen shot 2016-04-26 at 08 59 01" src="https://cloud.githubusercontent.com/assets/125676/14809424/3abb8db0-0b8d-11e6-8763-f3bfd07a9430.png">

compare to the actual numbers..
<img width="1147" alt="screen shot 2016-04-26 at 08 59 18" src="https://cloud.githubusercontent.com/assets/125676/14809423/3905d156-0b8d-11e6-9ea8-7fb50bda6b37.png">

**Comment by lipis** [comment]
Also here it says that I'm on rank 316 https://github-ranking.com/lipis while I can actually show you that you are off for at least 300+ people.. http://githubstats.lip.is/people/?limit=1024

(don't get me wrong.. I love your project and the idea.. but in the current state is not reflecting the reality)
