### ISSUE TITLE
user rankings don't consider user's contributions to organisations

### ISSUE THREAD

**Issue by balupton** [k0kubun/gitstar-ranking#40]
I do nearly all my work across my several opensource community orgs

https://gitstar-ranking.com/balupton is ranked 3361 yet https://gitstar-ranking.com/bevry is 1333

it would be accurate if user contributions also took into account their contributions across their organisations

**Comment by elliottzheng** [comment]
To encourage people in joining the opensource, I convert my personal project into an organization project, while I still do all most everything. However, the stars of the organization project didn't count for me, it doesn't sound right. And I also can't find my organization `CopyTranslator` in the ranking.

**Comment by k0kubun** [comment]
You need to login to add missing org right now due to past GitHub API changes. https://gitstar-ranking.com/copytranslator

**Comment by k0kubun** [comment]
While I can certainly understand this issue's motivation, how user's contributions to organisations should be considered is not really clear. 

For example, when a user fixes a single typo in an organisation repository, the user might get the same number of stars as the main maintainer who has implemented 99% of the work, which I think is not fair. On the other hand, if we choose some metrics like the number of commits to distribute stars across contributors, that might be also not fair for people making small commits vs big important changes. Therefore this is really hard to be neutral like existing features, so my proposal about this problem is that you should see an organisation which you contribute to as a part of your account, and see its rank instead. I hope you understand my concern and suggestion.
