### ISSUE TITLE
Organization is not found!

### ISSUE THREAD

**Issue by astorfi** [k0kubun/gitstar-ranking#44]
Thank you for your contribution.

gitstar-ranking cannot find my organization with Github address of https://github.com/osforscience. Do you know what is the problem?

Thanks

**Comment by k0kubun** [comment]
I see some worker errors and they may be related to yours as well. I guess its id is relatively big. going to fix it...

**Comment by k0kubun** [comment]
I fixed the error which I mentioned now, but it wasn't related to the issue that much.

The immediate cause of this problem is that GitHub's mind was changed after I created this app at first; They encouraged to call GitHub APIs in background without request, but it's now prohibited and such API calls result in client ban. Because of that, the feature to automatically add new users / organizations is disabled for now.

Anyway I'm planning to add a feature to add a new user when it's not found and the browsing user is logged in. I'll probably implement that in this weekend.

**Comment by astorfi** [comment]
@k0kubun Thank you for your reply. Bests
