### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by melissamcewen** [k0kubun/gitstar-ranking#55]
Went to send it to a colleague and it says "503 Service Temporarily Unavailable"
https://gitstar-ranking.com/

**Comment by k0kubun** [comment]
Hmm, my new letsencrypt renewal automation script had a bug making the site offline. I restarted the server and now it's online. Sorry for your inconvenience, I'll fix the automation later.

**Comment by melissamcewen** [comment]
Thank you! Love the site!

**Comment by chubin** [comment]
The site is down again

**Comment by k0kubun** [comment]
Thanks to report, I fixed it again. (I've gotta implement monitoring... 🙂)

This time, letsencrypt rotation itself automatically succeeded without the previous bug (yay, the certificate is new), but it hit another issue; I'm using very small servers to run it, and a new nginx ingress pod didn't start due to insufficient capacity. I temporarily stopped worker pod and now nginx ingress is working.

Not sure why it suddenly started to hit insufficient memory while I configure their quota, but I'll make sure I can notice it quickly by monitoring, in case the next cert rotation hits something new.

**Comment by KlausDevWalker** [comment]
Could [Infinity Free](https://infinityfree.net/) be a solution for this?
