### ISSUE TITLE
False Attribution - Don't count stars for forked repos / non-original to the user

### ISSUE THREAD

**Issue by HariSekhon** [k0kubun/gitstar-ranking#71]
Hi,

Thanks for your great work on this, I like it very much 👍 

Can I request 1 minor tweak to filter repos to only non-forks (in the GitHub API each repo has a `fork` field which should be set to `false` to be included).

Currently I can see forks of major projects where users mistakenly clicked a star on my fork of the project, giving me false credit for that major project, and listing those forked repos also balloons my list of repos on https://gitstar-ranking.com.

Right now I am about 30 stars over what I should be for my own personal projects because of these random stars on forks of repos that I happen to have made.

A crafty user could easily game this ranking system by simply going around forking all the most popular projects which would inevitably result in their forks gaining random stars that have nothing to do with their own work.

Even without gaming, right now the star stats are significantly inaccurate as long as they still include forked repos.

Thanks very much for reading.

Hari

**Comment by k0kubun** [comment]
> Thanks for your great work on this, I like it very much +1

Thanks :slightly_smiling_face: 

> Can I request 1 minor tweak to filter repos to only non-forks (in the GitHub API each repo has a fork field which should be set to false to be included).

Counting forks' stars is intended because `fork=true` doesn't always mean it's a false attribution. For example, I'd say https://github.com/shiftkey/desktop should be attributed to the forker, shiftkey, who did the significant amount of work on the fork. Would you say it's also a false attribution?

> Right now I am about 30 stars over what I should be for my own personal projects because of these random stars on forks of repos that I happen to have made.

I'd say the real problem here is that those spammers who give you random stars on fork repositories which really don't make any sense. WDYT?

> A crafty user could easily game this ranking system by simply going around forking all the most popular projects which would inevitably result in their forks gaining random stars that have nothing to do with their own work.

This has nothing to do with `fork=true`, because you could do the same thing in non-fork repositories. Even if we implement what you proposed, the same person could still create normal repositories and star them. For this issue, you should talk to GitHub support about banning self stars.
